# Generated by Django 4.0.6 on 2022-07-29 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('title_of_file', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique_for_date='uploaded')),
                ('body', models.TextField()),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('loading', 'Load'), ('uploaded', 'Uploaded')], default='draft', max_length=10)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fileExchange', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
