# Generated by Django 4.0.6 on 2022-07-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stoleAStone', '0002_document_rename_upload_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
        migrations.AddField(
            model_name='document',
            name='counter',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во загрузок'),
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
